Repository kleros/kleros-interaction, pull requests merged in 2018-11, with the labels that each got.

#171 chore(multiple-arbitrable-transaction): set RAB pragma comment
  contracts/standard/arbitration/MultipleArbitrableTransaction.sol
Labels: Type: Maintenance :construction:

#176 fix(multiple-arbitrable-transaction): some fixes from Clement's review
  contracts/standard/arbitration/MultipleArbitrableTransaction.sol
Labels: Priority: High, Status: In Progress, Type: Maintenance :construction:

#180 fix: pre-review vulnerability fixes
  contracts/standard/arbitration/MultipleArbitrableTransaction.sol
  test/multiple-arbitrable-transaction.js
Labels: Priority: Critical :fire:, Status: In Progress, Type: Maintenance :construction:
