Repository kleros/kleros-interaction, pull requests merged in 2018-10, with the labels that each got.

#137 chore(abi): update abi smart contract
  package.json
Labels: Type: Maintenance :construction:

#129 feat(composed-arbitrable): implement
  contracts/standard/arbitration/AppealableArbitrator.sol
  contracts/standard/arbitration/Arbitrator.sol
  contracts/standard/arbitration/CentralizedArbitrator.sol
  contracts/standard/arbitration/EnhancedAppealableArbitrator.sol
  contracts/standard/arbitration/TwoPartyArbitrableEscrowPayment.sol
  contracts/standard/arbitration/composed-arbitrable/agreement/MultiPartyAgreements.sol
  contracts/standard/arbitration/composed-arbitrable/composed/MultiPartyInsurableArbitrableAgreementsBase.sol
  contracts/standard/arbitration/composed-arbitrable/evidence/MultiPartyEvidence.sol
  contracts/standard/arbitration/composed-arbitrable/example/TwoPartyArbitrableEscrowPayment.sol
  contracts/standard/arbitration/composed-arbitrable/example/TwoPartyArbitrableEscrowPaymentProxyUser.sol
  contracts/standard/arbitration/composed-arbitrable/fee/MultiPartyInsurableFees.sol
  contracts/standard/arbitration/composed-arbitrable/proxy/ArbitrableProxy.sol
  contracts/standard/arbitration/composed-arbitrable/proxy/ArbitrableProxyUser.sol
  contracts/standard/arbitration/composed-arbitrable/proxy/MultiPartyInsurableArbitrableAgreementsProxy.sol
  test/two-party-arbitrable-escrow-payment-proxy-user.js
  test/two-party-arbitrable-escrow-payment.js
Labels: Priority: High, Status: Review Needed, Type: Enhancement :sparkles:

#145 test file for AppealableArbitrator.sol
  test/appealable-arbitrator.js
Labels: Priority: Medium, Status: Review Needed, Type: Maintenance :construction:

#149 fix(multiplearbitrablepayment): use transactionId instead disputeId
  contracts/standard/arbitration/MultipleArbitrableTransaction.sol
Labels: Priority: Critical :fire:, Type: Bug :bug:

#153 fix(multiple-arbitrable-payment): handle no ruling
  contracts/standard/arbitration/MultipleArbitrableTransaction.sol
  test/multiple-arbitrable-transaction.js
Labels: Priority: High, Type: Bug :bug:

#155 fix bad reference to the smart contract / arbitrableKitty test
  contracts/standard/arbitration/SimpleTwoPartyArbitrableEscrowPayment.sol
  test/arbitrable-kitty.js
Labels: Priority: High, Type: Bug :bug:

#156 chore(release): 0.1.0
  CHANGELOG.md
  package.json
Labels: Priority: High, Type: Maintenance :construction:

#131 Testing Arbitrator Versioning Proxy
  contracts/standard/proxy/ArbitratorVersioningProxy.sol
  contracts/standard/proxy/VersioningProxy.sol
  test/arbitrator-versioning-proxy.js
Labels: Priority: High, Status: Review Needed, Type: Enhancement :sparkles:

#135 Adding token2 curated list contract
  contracts/standard/arbitration/composed-arbitrable/example/ArbitrableTokenList.sol
  migrations/2_deploy_contracts.js
  test/arbitrable-token-list.js
Labels: Priority: High, Status: Review Needed, Type: Enhancement :sparkles:

#146 feat(bonding-curve): implement bonding curve contract
  contracts/standard/bonding-curve/BondingCurve.sol
  package.json
  test/bonding-curve.js
  yarn.lock
Labels: Priority: High, Status: Review Needed, Type: Enhancement :sparkles:
