Repository kleros/kleros-interaction, pull requests merged in 2019-02, with the labels that each got.

#212 TCR review suggestions implementation
  contracts/libraries/CappedMath.sol
  contracts/standard/permission/ArbitrableAddressList.sol
  contracts/standard/permission/ArbitrableTokenList.sol
  test/arbitrable-address-list.js
  test/arbitrable-token-list.js
Labels: Status: In Progress

#218 Refactor/escrow terminology
  CHANGELOG.md
  contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol
  contracts/standard/arbitration/MultipleArbitrableTransaction.sol
  package.json
  test/multiple-arbitrable-token-transaction.js
  test/multiple-arbitrable-transaction.js
Labels: Status: In Progress

#220 fix(token-escrow): check if the `transfer` fn failed
  contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol
  contracts/standard/arbitration/MultipleArbitrableTransaction.sol
Labels: Status: In Progress

#221 Implement TCR review suggestions
  contracts/standard/permission/ArbitrableAddressList.sol
  contracts/standard/permission/ArbitrableTokenList.sol
  test/arbitrable-address-list.js
  test/arbitrable-token-list.js
Labels: Status: In Progress

#223 refacto(escrow): remove useless storage variable
  contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol
  contracts/standard/arbitration/MultipleArbitrableTransaction.sol
  test/multiple-arbitrable-token-transaction.js
  test/multiple-arbitrable-transaction.js
Labels: Status: In Progress, Status: Review Needed, Type: Enhancement :sparkles:

#225 Feat: Review Suggestions
  contracts/standard/permission/ArbitrableAddressList.sol
  contracts/standard/permission/ArbitrableTokenList.sol
  package.json
  test/arbitrable-address-list.js
  test/arbitrable-token-list.js
  truffle.js
Labels: Status: In Progress

#226 Feat/evidence groups
  contracts/standard/arbitration/ArbitrableDeposit.sol
  contracts/standard/arbitration/IArbitrable.sol
  contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol
  contracts/standard/arbitration/MultipleArbitrableTransaction.sol
  contracts/standard/arbitration/SimpleTwoPartyArbitrableEscrowPayment.sol
  contracts/standard/arbitration/TwoPartyArbitrable.sol
  contracts/standard/arbitration/TwoPartyArbitrableEscrowPayment.sol
  contracts/standard/permission/ArbitrableAddressList.sol
  contracts/standard/permission/ArbitrablePermissionList.sol
  contracts/standard/permission/ArbitrableTokenList.sol
  contracts/standard/proxy/RealitioArbitratorProxy.sol
Labels: Status: In Progress

#227 chore(ArbitrableTokenList): add removed require messages as comments
  contracts/standard/permission/ArbitrableTokenList.sol
Labels: Status: In Progress

#228 chore: v0.7.0
  package.json
Labels: Status: In Progress

#230 fix(escrows): fix typos
  contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol
  contracts/standard/arbitration/MultipleArbitrableTransaction.sol
Labels: Status: In Progress

#233 feat(base-deposit): challenger & request can be !=
  contracts/standard/permission/ArbitrableTokenList.sol
  test/arbitrable-token-list.js
Labels: Status: In Progress, Status: Review Needed

#234 feat(escrows): implement arbitrable interface
  contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol
  contracts/standard/arbitration/MultipleArbitrableTransaction.sol
Labels: Priority: High, Status: In Progress, Status: Review Needed, Type: Maintenance :construction:
